
/** @class Provides usefull functions and properties for public usage. */
export class Utilities {

    /** @field Represents the month's name on a year. */
    private static readonly months: Array<string> = [
        "",
        "January",
        "February",
        "March",
        "April",
        "May",
        "June",
        "July",
        "August",
        "September",
        "October",
        "November",
        "December"
    ]

    /**
     * Returns the name of the month with the given numeric representation.
     * @param index {number} The one-based of the month to return.
     * @returns {string} The name of the month.
     */
    public static getMonthName(index: number): string {
        let x: string = Utilities.months[index];
        return x;
    }

    /**
     * Applies the given function to all the items in a list.
     * @param T The type of the given list.
     * @param items {T} The list over which to iterate.
     * @param mergeItem {(T): string} A function that translates tehe given item to a string representation.
     * @returns {string} All the items's strings generated by the given method, concatenated.
     */
    public static mergeItems<T>(items: T[], mergeItem: (item: T) => string): string {
        let answer: string = "";
        for(let i = 0; i < items.length; i++) {
            answer += mergeItem(items[i]);
        }
        return answer;
    }

    /**
     * @deprecated Do not use this
     * Sets the current page.
     * @param index {number} The index of the page to activate.
     */
    public static setCurrentPage(index: number): void {
        let pages: NodeListOf<Element> = document.querySelectorAll<Element>("main > div");
        for(let i = 0; i < pages.length; i++) {
            pages[i].classList.add("hidden-content");
            if(i == index) {
                pages[i].classList.remove("hidden-content");
            }
        }
        let navbar: Element | null = document.querySelector<Element>(".navbar-collapse");
        //navbar.collapse("hide");
    }

}

export default Utilities;